### ISSUE TITLE
Full process definition in config file

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/faim-wako-searchfirst#33]
I would be nice if we can keep the run script general, and have full flexibility in defining the processing via the config file.

```
steps:
  - segment: cellpose
  - filter:  # all functions should accept 'labels' and change inplace (and an optional other_channel argument?)
    - bounding_box
    - object_size
  - sample: grid

cellpose:
  - model: /path/to/model
  - diameter: 50.0
  - cellprob_threshold: 0.0
  - flow_threshold: 0.4

bounding_box:
  - min_x: 0
  - min_y: 0
  - max_x: 2000
  - max_y: 2000

object_size:
  - min_size: 100
```

The items in `steps` should correspond to functions in the `faim_wako_searchfirst.segment`, `faim_wako_searchfirst.filter` and `faim_wako_searchfirst.sample` modules, respectively.

In addition to `steps`, each function's arguments are listed under the function name. (This entry should be optional if the function requires no additional arguments.)
