### ISSUE TITLE
Expose min and max parameters for size and eccentricity

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/faim-wako-searchfirst#4]
```yaml
segmentation:
    threshold: 128
    include_holes: yes
    min_size: 10
    min_size: 99999999999
    min_eccentricity: 0.0
    max_eccentricity: 0.9
```
