### ISSUE TITLE
Implement generic feature filter method

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/faim-wako-searchfirst#64]
Config:

```
process:
  filter: [feature]

feature:
  feature_name: solidity
  min_value: 0.8
  max_value: 1.0
```

This should delegate to the `feature_name` feature from `regionprops` and filter according to the given values.
